name: Build & Deploy

on:
  push:
    branches:
      - main   # 你主分支的名字，可能是 master，注意改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install minify tools
        run: |
          npm install terser clean-css-cli html-minifier-terser -g

      - name: Minify JS
        run: |
          mkdir -p dist/static/js
          for file in static/js/*.js; do
            terser "$file" -o "dist/$file" --compress --mangle
          done

      - name: Minify CSS
        run: |
          mkdir -p dist/static/css
          for file in static/css/*.css; do
            cleancss -o "dist/$file" "$file"
          done

      - name: Minify HTML
        run: |
          mkdir -p dist
          for file in *.html; do
            html-minifier-terser --collapse-whitespace --remove-comments -o "dist/$file" "$file"
          done

      - name: Copy other assets
        run: |
          rsync -av --exclude='*.html' --exclude='*.js' --exclude='*.css' ./ dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
