name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build dist folder
        run: |
          mkdir -p dist
          cp -r config.json dist/ || echo "no config.json"
          cp -r index.html dist/ || echo "no index.html"
          cp -r static dist/ || echo "no static folder"

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: moontv
          directory: dist
